version: '3.8'

services:
  mysql:
    container_name: mysql
    platform: linux/amd64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vcil
      MYSQL_ROOT_USER: root
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: adonis
      PMA_PASSWORD: adonis
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
      - $PWD/dockerConfig/mysql-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysqlnetwork
  
  redis:
    container_name: redis
    image: redis:6-alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379
    networks:
      - mysqlnetwork

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - mysql
      - redis
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      - DB_HOST=mysql  # Chỉ định DB_HOST như mysql
      - REDIS_HOST=redis  # Thêm REDIS_HOST
      - DB_PORT=${DB_PORT}  # Chỉ định DB_PORT từ .env
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch 

volumes:
  mysql_volume:
  redis_volume:
  
networks:
  mysqlnetwork:
    driver: bridge
